# Server configuration
server:
  port: 8081
  servlet:
    context-path: /identity



# Application properties
spring:
  application:
    name: identity-service

  # Datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


# JWT
jwt:
  expiration: 2592000 # 30 days = 30 * 24 * 60 * 60
  secretKey: LLaTGzHHnTJRbK0+yVZq3ff/H+/JRmmoK2SCMaaJ5Eo=
